export const queryKeys = {
  adminOverview: ['admin', 'overview'] as const,
  adminComments: (params?: Record<string, unknown>) => ['admin', 'comments', params ?? {}] as const,
  bookmarks: (params?: Record<string, unknown>) => ['bookmarks', params ?? {}] as const,
  bookmarkStatus: (guideId: string | undefined) => ['bookmarks', 'guide', guideId ?? ''] as const,
  categories: (params?: Record<string, unknown>) => ['categories', params ?? {}] as const,
  category: (slug: string | undefined) => ['categories', 'slug', slug ?? ''] as const,
  guides: (params?: Record<string, unknown>) => ['guides', params ?? {}] as const,
  guide: (slug: string | undefined) => ['guides', 'slug', slug ?? ''] as const,
  guideComments: (guideId: string | undefined, params?: Record<string, unknown>) => ['comments', 'guide', guideId ?? '', params ?? {}] as const,
  myComments: (params?: Record<string, unknown>) => ['comments', 'me', params ?? {}] as const,
  search: (params?: Record<string, unknown>) => ['search', params ?? {}] as const,
  users: (params?: Record<string, unknown>) => ['users', params ?? {}] as const,
  me: ['users', 'me'] as const,
  userDashboard: ['users', 'me', 'dashboard'] as const,
};
